language: php

services:
 - mysql
php:
  - 7.2
  - 7.1
  - 7.0
  - hhvm

before_script:
  - cp .env.travis .env
  - mysql -e 'CREATE DATABASE restapi_test;'
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit