version: '3'
services:
  restapi-app:
    depends_on:
      - restapi-mysql
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: restapi/php-nginx
    environment:
      XDEBUG_HOST : ${XDEBUG_HOST}
    ports:
      - "${APP_PORT}:80"
    volumes:
      - .:/var/www/html
    networks:
      - restapi_docker
  restapi-redis:
    image: redis:alpine
    networks:
      - restapi_docker
  restapi-mysql:
    image: mysql:5.7
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: restapi
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    volumes:
      - rapimsqldata:/var/lib/mysql
    networks:
      - restapi_docker
networks:
  restapi_docker:
    driver: "bridge"
volumes:
  rapimsqldata:
    driver: "local"